# Generated by Django 2.1.5 on 2019-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181229_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StuID', models.CharField(max_length=20)),
                ('Height', models.CharField(max_length=8)),
                ('Weight', models.CharField(max_length=5)),
                ('HWScore', models.CharField(max_length=3)),
                ('HWLevel', models.TextField()),
                ('LungVolume', models.CharField(max_length=5)),
                ('LungScore', models.CharField(max_length=3)),
                ('LungLevel', models.TextField()),
                ('Meter50', models.CharField(max_length=5)),
                ('Meter50Score', models.CharField(max_length=3)),
                ('Meter50Level', models.TextField()),
                ('Crook', models.CharField(max_length=5)),
                ('CrookScore', models.CharField(max_length=3)),
                ('CrookLevel', models.TextField()),
                ('Jump', models.CharField(max_length=3)),
                ('JumpScore', models.CharField(max_length=3)),
                ('JumpLevel', models.TextField()),
                ('Strength', models.CharField(max_length=3)),
                ('StrengthScore', models.CharField(max_length=3)),
                ('StrengthLevel', models.TextField()),
                ('Meter8001000', models.CharField(max_length=5)),
                ('Meter8001000Score', models.CharField(max_length=3)),
                ('Meter8001000Level', models.TextField()),
                ('TotalScore', models.CharField(max_length=3)),
                ('TotalLevel', models.TextField()),
                ('School', models.TextField()),
                ('Grade', models.CharField(max_length=10)),
                ('Semester', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterveneSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_state', models.CharField(max_length=10)),
                ('is_fail_exam', models.BooleanField()),
                ('body_health_state', models.TextField()),
                ('treatment_count', models.CharField(max_length=10)),
                ('moral', models.TextField()),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Intervene',
        ),
        migrations.AddField(
            model_name='moral',
            name='Grade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='moral',
            name='School',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='score',
            name='Grade',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='basic',
            name='Gender',
            field=models.TextField(),
        ),
    ]
